version: '2'

services:
  DOTHROKU_CONTAINER_NAME:
    image: DOTHROKU_IMAGE_NAME
    command: bash -c "rails-init && /sbin/my_init"
    container_name: DOTHROKU_CONTAINER_NAME
    restart: always
    networks:
      - dothroku_nginx
      - DOTHROKU_NETWORK_NAME
    environment:
      - VIRTUAL_HOST=DOTHROKU_HOSTNAME
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=DOTHROKU_HOSTNAME
      - LETSENCRYPT_EMAIL=DOTHROKU_EMAIL
      - SECRET_KEY_BASE=testy123
      - REDISCLOUD_URL=redis://redis_chat_app:6379
networks:
  dothroku_nginx:
    external:
      name: dothroku_nginx
  DOTHROKU_NETWORK_NAME:
    external:
      name: DOTHROKU_NETWORK_NAME

#${SECRET_KEY_BASE}

