version: '2'

services:
  test_redis:
    image: redis
    container_name: test_redis
    networks:
      - app_network
  DOTHROKU_CONTAINER_NAME:
    image: DOTHROKU_IMAGE_NAME
    command: bash -c "rails-init && /sbin/my_init"
    container_name: DOTHROKU_CONTAINER_NAME
    restart: always
    networks:
      - dothroku_nginx
      - app_network
    depends_on:
      - test_redis
    environment:
      - VIRTUAL_HOST=DOTHROKU_HOSTNAME
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=DOTHROKU_HOSTNAME
      - LETSENCRYPT_EMAIL=DOTHROKU_EMAIL
      - SECRET_KEY_BASE=testy123
      - REDISCLOUD_URL=redis://test_redis:6379
networks:
  dothroku_nginx:
    external:
      name: dothroku_nginx
  app_network:

#${SECRET_KEY_BASE}

