default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dothroku_development

test:
  <<: *default
  database: dothroku_test

production:
  <<: *default
  database: dothroku_production
