default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dothroku_development
  username: postgres
  password:

test:
  <<: *default
  database: dothroku_test
  username: postgres
  password:

production:
  <<: *default
  database: dothroku_production
  username: root
  password:
